"""One-shot script: writes the new clean dashboard HTML to src/templates/dashboard.html"""
import os, pathlib

ROOT = pathlib.Path(__file__).parent.parent
OUT  = ROOT / "src" / "templates" / "dashboard.html"

HTML = (
    '<!DOCTYPE html>\n'
    '<html lang="en">\n'
    '<head>\n'
    '<meta charset="UTF-8">\n'
    '<meta name="viewport" content="width=device-width,initial-scale=1.0,viewport-fit=cover">\n'
    '<meta name="mobile-web-app-capable" content="yes">\n'
    '<meta name="apple-mobile-web-app-capable" content="yes">\n'
    '<meta name="theme-color" content="#070a10">\n'
    '<title>Bettor AI</title>\n'
    '<style>\n'
    '*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}\n'
    ':root{\n'
    '  --bg:#070a10;--sur:#0e1118;--s2:#141820;--s3:#1a2030;\n'
    '  --bd:#1e2535;--bd2:#2a3450;--tx:#dde4f0;--mt:#7a8aa8;--mt2:#3d4f6a;\n'
    '  --gr:#22c55e;--gd:#0a1e10;--gd2:#0d2a14;\n'
    '  --yw:#f0b429;--yd:#1f1a08;\n'
    '  --re:#ef4444;--rd:#1f0a0a;\n'
    '  --bl:#3b82f6;--bld:#0a1020;\n'
    '  --pu:#a855f7;--pd:#160d24;\n'
    '  --or:#f97316;--od:#1f1208;\n'
    '  --tl:#14b8a6;--tld:#081a18;\n'
    '  --r:10px;--rl:14px;\n'
    '}\n'
    'body{background:var(--bg);color:var(--tx);font-family:"Segoe UI",system-ui,sans-serif;font-size:14px;line-height:1.5;min-height:100vh;overflow-x:hidden;-webkit-font-smoothing:antialiased}\n'
    '.page{max-width:1200px;margin:0 auto;padding:12px 12px 80px;padding-bottom:calc(80px + env(safe-area-inset-bottom))}\n'
    '/* HEADER */\n'
    '.hdr{display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:10px;margin-bottom:16px;padding-bottom:12px;border-bottom:1px solid var(--bd)}\n'
    '.brand{display:flex;align-items:center;gap:10px}\n'
    '.logo{width:40px;height:40px;border-radius:11px;background:linear-gradient(135deg,#22c55e,#0d9488);display:flex;align-items:center;justify-content:center;font-size:20px;font-weight:900;color:#000;flex-shrink:0}\n'
    '.brand-text h1{font-size:1.2rem;font-weight:900;letter-spacing:-.5px}\n'
    '.brand-text h1 em{color:var(--gr);font-style:normal}\n'
    '.brand-text p{font-size:10px;color:var(--mt)}\n'
    '.hdr-right{display:flex;align-items:center;gap:6px;flex-wrap:wrap}\n'
    '.status-pill{display:inline-flex;align-items:center;gap:5px;padding:5px 12px;border-radius:999px;font-size:11px;font-weight:700;border:1px solid transparent}\n'
    '.status-pill.idle{background:var(--s2);color:var(--mt);border-color:var(--bd)}\n'
    '.status-pill.running{background:var(--gd);color:var(--gr);border-color:#22c55e55}\n'
    '.status-pill.done{background:var(--gd);color:var(--gr);border-color:#22c55e44}\n'
    '.status-pill.error{background:var(--rd);color:var(--re);border-color:#ef444455}\n'
    '.sdot{width:7px;height:7px;border-radius:50%;flex-shrink:0}\n'
    '.sdot.idle{background:var(--mt)}.sdot.running{background:var(--gr);animation:pulse 1s infinite}.sdot.done{background:var(--gr)}.sdot.error{background:var(--re)}\n'
    '@keyframes pulse{0%,100%{opacity:1}50%{opacity:.25}}\n'
    '.run-btn{background:linear-gradient(135deg,#22c55e,#0d9488);color:#000;border:none;padding:9px 22px;border-radius:var(--r);font-weight:800;font-size:13px;cursor:pointer;transition:opacity .15s,transform .1s}\n'
    '.run-btn:hover{opacity:.88;transform:translateY(-1px)}\n'
    '.run-btn:disabled{opacity:.3;cursor:not-allowed;transform:none}\n'
    '.console-btn{background:var(--s2);color:var(--mt);border:1px solid var(--bd);padding:7px 13px;border-radius:var(--r);font-size:11px;font-weight:700;cursor:pointer;transition:all .15s}\n'
    '.console-btn:hover{border-color:var(--tl);color:var(--tl)}\n'
    '/* PROGRESS */\n'
    '.prog-wrap{background:var(--sur);border:1px solid var(--bd);border-radius:var(--r);padding:14px 16px;margin-bottom:20px;display:none}\n'
    '.prog-wrap.on{display:block}\n'
    '.prog-head{display:flex;justify-content:space-between;font-size:11px;color:var(--mt);margin-bottom:8px}\n'
    '.prog-track{height:5px;background:var(--s3);border-radius:999px;overflow:hidden;margin-bottom:10px}\n'
    '.prog-fill{height:100%;background:linear-gradient(90deg,var(--gr),var(--tl));border-radius:999px;transition:width .5s ease}\n'
    '.phase-chips{display:flex;flex-wrap:wrap;gap:4px}\n'
    '.pchip{font-size:9px;padding:2px 8px;border-radius:999px;background:var(--s2);color:var(--mt2);border:1px solid var(--bd)}\n'
    '.pchip.act{background:var(--gd);color:var(--gr);border-color:#22c55e44}\n'
    '.pchip.done{background:var(--s3);color:var(--mt)}\n'
    '.err-box{background:var(--rd);border:1px solid var(--re);border-radius:var(--r);padding:12px 14px;color:var(--re);font-family:monospace;font-size:11px;white-space:pre-wrap;overflow-x:auto;margin-bottom:16px}\n'
    '/* TABS */\n'
    '.tabs{display:flex;gap:0;border-bottom:2px solid var(--bd);margin-bottom:18px;overflow-x:auto;scrollbar-width:none}\n'
    '.tabs::-webkit-scrollbar{display:none}\n'
    '.tab{padding:9px 20px;font-size:12px;font-weight:800;color:var(--mt);border:none;background:none;cursor:pointer;border-bottom:3px solid transparent;margin-bottom:-2px;transition:color .15s,border-color .15s;text-transform:uppercase;letter-spacing:.4px;display:flex;align-items:center;gap:6px;white-space:nowrap;flex-shrink:0}\n'
    '.tab:hover{color:var(--tx)}\n'
    '.tab.act{color:var(--gr);border-bottom-color:var(--gr)}\n'
    '.tab-cnt{background:var(--s3);color:var(--mt);font-size:9px;font-weight:700;padding:1px 6px;border-radius:999px}\n'
    '.tab.act .tab-cnt{background:var(--gd);color:var(--gr)}\n'
    '.tab-panel{display:none}.tab-panel.on{display:block}\n'
    '/* BADGES */\n'
    '.sbadge{display:inline-flex;align-items:center;padding:3px 9px;border-radius:999px;font-size:9px;font-weight:900;letter-spacing:.4px;white-space:nowrap}\n'
    '.sbadge.ELITE{background:var(--gd2);color:#22c55e;border:1px solid #22c55e44}\n'
    '.sbadge.SAFE{background:var(--tld);color:#14b8a6;border:1px solid #14b8a644}\n'
    '.sbadge.MODERATE{background:var(--yd);color:#f0b429;border:1px solid #f0b42944}\n'
    '.sbadge.RISKY{background:var(--rd);color:#ef4444;border:1px solid #ef444444}\n'
    '.wbadge{display:inline-flex;align-items:center;padding:2px 8px;border-radius:5px;font-size:9px;font-weight:800;white-space:nowrap}\n'
    '.wbadge.LIVE{background:var(--rd);color:var(--re);border:1px solid #ef444444;animation:pulse 1.4s infinite}\n'
    '.wbadge.TODAY{background:var(--gd);color:var(--gr);border:1px solid #22c55e44}\n'
    '.wbadge.TOMORROW{background:var(--od);color:var(--or);border:1px solid #f9731644}\n'
    '.wbadge.UPCOMING{background:var(--s3);color:var(--mt);border:1px solid var(--bd)}\n'
    '.sport-chip{font-size:9px;font-weight:800;text-transform:uppercase;letter-spacing:.5px;padding:2px 7px;border-radius:4px}\n'
    '.sport-chip.MLB{background:var(--bld);color:var(--bl)}\n'
    '.sport-chip.SOCCER{background:var(--gd);color:var(--gr)}\n'
    '/* GAME CARD */\n'
    '.game-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(min(360px,100%),1fr));gap:12px}\n'
    '.game-card{background:var(--sur);border:1px solid var(--bd);border-radius:var(--rl);overflow:hidden;transition:border-color .15s,transform .1s,box-shadow .15s}\n'
    '.game-card:hover{border-color:var(--bd2);transform:translateY(-1px);box-shadow:0 4px 20px rgba(0,0,0,.35)}\n'
    '.game-card.ELITE{border-top:3px solid #22c55e}.game-card.SAFE{border-top:3px solid #14b8a6}\n'
    '.game-card.MODERATE{border-top:3px solid #f0b429}.game-card.RISKY{border-top:3px solid #ef4444}\n'
    '.game-card.LIVE-GAME{border-color:#ef444499!important}\n'
    '.gc-hdr{padding:12px 14px 8px;display:flex;justify-content:space-between;align-items:flex-start;gap:6px}\n'
    '.gc-hdr-left{display:flex;flex-direction:column;gap:4px;min-width:0;flex:1}\n'
    '.gc-meta{display:flex;align-items:center;gap:5px;flex-wrap:wrap}\n'
    '.gc-matchup{font-size:.95rem;font-weight:800;line-height:1.2}\n'
    '.gc-away{color:var(--tx)}.gc-sep{color:var(--mt);font-weight:400;padding:0 4px}\n'
    '.gc-home{color:var(--mt)}\n'
    '.gc-starter{font-size:10px;color:var(--mt);margin-top:2px}\n'
    '.gc-starter span{color:var(--tx);font-weight:600}\n'
    '.gc-rows{display:flex;flex-direction:column}\n'
    '.gc-row{display:flex;align-items:center;gap:10px;padding:10px 14px;border-top:1px solid var(--bd)}\n'
    '.gc-row:hover{background:var(--s2)}\n'
    '.gc-type{font-size:8px;font-weight:900;letter-spacing:.8px;text-transform:uppercase;width:38px;flex-shrink:0;padding:3px 0;text-align:center;border-radius:4px}\n'
    '.gc-type.WIN{background:#052e1688;color:#22c55e}\n'
    '.gc-type.PROP{background:var(--bld);color:var(--bl)}\n'
    '.gc-type.GAME{background:var(--pd);color:var(--pu)}\n'
    '.gc-type.NONE{background:var(--s3);color:var(--mt2)}\n'
    '.gc-content{flex:1;min-width:0}\n'
    '.gc-label{font-size:.88rem;font-weight:700;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}\n'
    '.gc-sublabel{font-size:10px;color:var(--mt);margin-top:1px}\n'
    '.gc-bar{height:2px;border-radius:999px;margin-top:4px;max-width:100%}\n'
    '.gc-bar.WIN{background:linear-gradient(90deg,#22c55e,#16a34a)}\n'
    '.gc-bar.PROP{background:linear-gradient(90deg,var(--bl),#6366f1)}\n'
    '.gc-bar.GAME{background:linear-gradient(90deg,var(--pu),#7c3aed)}\n'
    '.gc-right{display:flex;flex-direction:column;align-items:flex-end;gap:3px;flex-shrink:0}\n'
    '.gc-conf{font-size:1.0rem;font-weight:900;line-height:1}\n'
    '.gc-conf.ELITE{color:#22c55e}.gc-conf.SAFE{color:#14b8a6}\n'
    '.gc-conf.MODERATE{color:#f0b429}.gc-conf.RISKY{color:#ef4444}\n'
    '.gc-odds{font-size:10px;color:var(--bl);font-weight:700}\n'
    '.live-banner{background:linear-gradient(90deg,#ef4444cc,#dc2626cc);color:#fff;padding:5px 14px;font-size:10px;font-weight:900;letter-spacing:1.5px;display:flex;align-items:center;gap:6px;animation:pulse 1.4s infinite}\n'
    '/* PARLAY */\n'
    '.parlay-header{display:flex;align-items:center;gap:10px;margin-bottom:16px;flex-wrap:wrap}\n'
    '.parlay-header h2{font-size:1.1rem;font-weight:900;flex:1}\n'
    '.parlay-subtext{font-size:11px;color:var(--mt)}\n'
    '.parlay-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(min(320px,100%),1fr));gap:12px}\n'
    '.parl-card{background:var(--sur);border:1px solid var(--bd);border-radius:var(--rl);overflow:hidden;transition:border-color .15s,transform .1s}\n'
    '.parl-card:hover{border-color:var(--bd2);transform:translateY(-1px)}\n'
    '.parl-card.ELITE{border-top:3px solid #22c55e}.parl-card.SAFE{border-top:3px solid #14b8a6}\n'
    '.parl-card.MODERATE{border-top:3px solid #f0b429}.parl-card.RISKY{border-top:3px solid #ef4444}\n'
    '.parl-card.top-pick{border-color:#22c55e88;box-shadow:0 0 0 2px #22c55e22}\n'
    '.parl-hdr{padding:12px 14px 8px;display:flex;align-items:center;gap:8px;flex-wrap:wrap}\n'
    '.parl-n-badge{font-size:11px;font-weight:900;padding:4px 12px;border-radius:999px;background:var(--pd);color:var(--pu);border:1px solid #a855f744;white-space:nowrap}\n'
    '.parl-rec-badge{font-size:9px;font-weight:900;padding:2px 8px;border-radius:999px;background:#052e16;color:#22c55e;border:1px solid #22c55e44}\n'
    '.parl-stats{display:flex;gap:14px;padding:0 14px 10px;flex-wrap:wrap}\n'
    '.pstat{font-size:11px;color:var(--mt)}.pstat span{font-weight:800;color:var(--tx)}\n'
    '.pstat span.gr{color:#22c55e}.pstat span.pu{color:var(--pu)}.pstat span.yw{color:#f0b429}\n'
    '.parl-legs{padding:0 14px 12px}\n'
    '.parl-leg-item{display:flex;align-items:flex-start;gap:8px;padding:6px 0;border-bottom:1px solid var(--bd);font-size:12px}\n'
    '.parl-leg-item:last-child{border-bottom:none}\n'
    '.parl-leg-num{font-size:9px;font-weight:900;width:16px;height:16px;border-radius:50%;background:var(--s3);color:var(--mt);display:flex;align-items:center;justify-content:center;flex-shrink:0;margin-top:2px}\n'
    '.parl-leg-label{flex:1;font-weight:600;line-height:1.3}\n'
    '.parl-leg-conf{font-size:10px;font-weight:800;color:#22c55e;flex-shrink:0}\n'
    '.sbadge-sm{font-size:8px;font-weight:900;padding:1px 5px;border-radius:3px;flex-shrink:0}\n'
    '.sbadge-sm.ELITE{background:var(--gd);color:#22c55e}.sbadge-sm.SAFE{background:var(--tld);color:#14b8a6}\n'
    '.sbadge-sm.MODERATE{background:var(--yd);color:#f0b429}.sbadge-sm.RISKY{background:var(--rd);color:#ef4444}\n'
    '/* SKELETON */\n'
    '@keyframes shimmer{0%{background-position:-600px 0}100%{background-position:600px 0}}\n'
    '.sk{background:linear-gradient(90deg,var(--s2) 25%,var(--s3) 50%,var(--s2) 75%);background-size:600px 100%;animation:shimmer 1.6s infinite;border-radius:5px}\n'
    '.sk-card{background:var(--sur);border:1px solid var(--bd);border-radius:var(--rl);padding:16px;height:220px;overflow:hidden}\n'
    '.sk-card .sk{margin-bottom:10px}\n'
    '/* EMPTY STATE */\n'
    '.empty{padding:40px 16px;text-align:center;color:var(--mt);grid-column:1/-1}\n'
    '.empty-icon{font-size:2.5rem;margin-bottom:10px;display:block}\n'
    '.empty strong{display:block;color:var(--tx);font-size:1rem;margin-bottom:6px}\n'
    '.empty p{font-size:12px;max-width:320px;margin:0 auto;line-height:1.6}\n'
    '/* CONSOLE */\n'
    '.console-wrap{position:fixed;bottom:0;left:0;right:0;z-index:900;transform:translateY(100%);transition:transform .3s cubic-bezier(.4,0,.2,1)}\n'
    '.console-wrap.open{transform:translateY(0)}\n'
    '.console-pull{background:var(--s2);border-top:1px solid var(--tl);padding:7px 18px;display:flex;align-items:center;justify-content:space-between;cursor:pointer}\n'
    '.cpull-l{display:flex;align-items:center;gap:8px;font-size:11px;font-weight:700;font-family:monospace;color:var(--tl)}\n'
    '.cpull-dot{width:7px;height:7px;border-radius:50%;background:var(--mt2)}\n'
    '.cpull-dot.act{background:var(--gr);animation:pulse 1s infinite}\n'
    '.cpull-badge{font-size:10px;background:var(--s3);color:var(--mt);padding:1px 7px;border-radius:999px;font-family:monospace}\n'
    '.console-body{background:#030608;max-height:260px;overflow-y:auto;padding:10px 18px;font-family:"Cascadia Code","Fira Code","Consolas",monospace;font-size:11px;line-height:1.65}\n'
    '.lg{display:flex;gap:8px;color:#5a7090}\n'
    '.lg .ts{color:#2d4055;flex-shrink:0}\n'
    '.lg .msg{word-break:break-word}\n'
    '.lg.err .msg{color:#ef4444}.lg.warn .msg{color:#f0b429}.lg.ok .msg{color:#22c55e}.lg.phase .msg{color:#a855f7;font-weight:700}\n'
    '.lg-empty{color:#2d4055;font-style:italic}\n'
    '::-webkit-scrollbar{width:5px;height:5px}\n'
    '::-webkit-scrollbar-track{background:var(--s2)}\n'
    '::-webkit-scrollbar-thumb{background:var(--mt2);border-radius:3px}\n'
    '/* RESPONSIVE */\n'
    '@media(max-width:480px){\n'
    '  .page{padding:8px 8px 76px}\n'
    '  .hdr{flex-direction:column;align-items:flex-start}\n'
    '  .hdr-right{width:100%;justify-content:space-between}\n'
    '  .run-btn{flex:1;text-align:center}\n'
    '  .tabs{flex-wrap:nowrap}\n'
    '  .tab{padding:8px 12px;font-size:11px}\n'
    '  .tab-cnt{display:none}\n'
    '  .game-grid,.parlay-grid{grid-template-columns:1fr;gap:8px}\n'
    '}\n'
    '@media(min-width:481px) and (max-width:640px){\n'
    '  .game-grid,.parlay-grid{grid-template-columns:1fr}\n'
    '  .tabs{flex-wrap:nowrap;overflow-x:auto;scrollbar-width:none}\n'
    '  .tab{flex-shrink:0}\n'
    '}\n'
    '@media(hover:none){.game-card:hover,.parl-card:hover{transform:none;box-shadow:none}.run-btn:hover{opacity:1;transform:none}}\n'
    '@supports(padding-bottom:env(safe-area-inset-bottom)){\n'
    '  .console-wrap{padding-bottom:env(safe-area-inset-bottom)}\n'
    '  .page{padding-left:max(12px,env(safe-area-inset-left));padding-right:max(12px,env(safe-area-inset-right))}\n'
    '}\n'
    '/* SPLASH */\n'
    '#splash{position:fixed;inset:0;z-index:9999;background:var(--bg);display:flex;flex-direction:column;align-items:center;justify-content:center;transition:opacity .5s ease,visibility .5s ease;overflow:hidden}\n'
    '#splash.hidden{opacity:0;visibility:hidden;pointer-events:none}\n'
    '#splash-particles{position:absolute;inset:0;overflow:hidden;pointer-events:none}\n'
    '.sp-dot{position:absolute;border-radius:50%;animation:sp-float linear infinite;opacity:0}\n'
    '@keyframes sp-float{0%{transform:translateY(0) scale(1);opacity:0}10%{opacity:.6}90%{opacity:.3}100%{transform:translateY(-110vh) scale(.4);opacity:0}}\n'
    '.splash-logo{width:80px;height:80px;border-radius:22px;background:linear-gradient(135deg,#22c55e,#0d9488);display:flex;align-items:center;justify-content:center;font-size:40px;font-weight:900;color:#000;box-shadow:0 0 50px #22c55e55;animation:logo-breathe 2.5s ease-in-out infinite;margin-bottom:22px}\n'
    '@keyframes logo-breathe{0%,100%{box-shadow:0 0 40px #22c55e44;transform:scale(1)}50%{box-shadow:0 0 70px #22c55e88;transform:scale(1.04)}}\n'
    '.splash-title{font-size:2rem;font-weight:900;letter-spacing:-.5px;margin-bottom:4px}\n'
    '.splash-title em{color:var(--gr);font-style:normal}\n'
    '.splash-sub{font-size:12px;color:var(--mt);margin-bottom:36px}\n'
    '.splash-stages{display:flex;flex-direction:column;gap:8px;width:min(380px,88vw);margin-bottom:28px}\n'
    '.spl-stage{display:flex;align-items:center;gap:10px;font-size:12px;color:var(--mt2);transition:color .3s}\n'
    '.spl-stage.done{color:var(--mt)}.spl-stage.act{color:var(--gr);font-weight:700}\n'
    '.spl-stage-icon{width:22px;height:22px;border-radius:50%;flex-shrink:0;display:flex;align-items:center;justify-content:center;font-size:10px;background:var(--s3);color:var(--mt2);border:1px solid var(--bd);transition:all .3s}\n'
    '.spl-stage.done .spl-stage-icon{background:var(--gd);color:var(--gr);border-color:#22c55e44}\n'
    '.spl-stage.act .spl-stage-icon{background:var(--gd);color:var(--gr);border-color:#22c55e88;animation:spl-spin 1s linear infinite}\n'
    '@keyframes spl-spin{to{transform:rotate(360deg)}}\n'
    '.spl-stage-lbl{flex:1}\n'
    '.spl-stage-val{font-size:10px;font-weight:800;color:var(--gr);margin-left:auto}\n'
    '.splash-bar-wrap{width:min(380px,88vw);margin-bottom:8px}\n'
    '.splash-bar-track{height:3px;background:var(--s3);border-radius:999px;overflow:hidden}\n'
    '.splash-bar-fill{height:100%;border-radius:999px;background:linear-gradient(90deg,var(--gr),var(--tl),var(--bl));background-size:200% 100%;animation:bar-shine 1.8s linear infinite;transition:width .5s ease;width:0%}\n'
    '@keyframes bar-shine{0%{background-position:100% 0}100%{background-position:-100% 0}}\n'
    '.splash-pct{font-size:10px;color:var(--mt);text-align:right;margin-top:4px}\n'
    '.splash-db-strip{display:flex;gap:20px;flex-wrap:wrap;justify-content:center;padding:10px 20px;border-radius:10px;border:1px solid var(--bd);background:var(--s2)}\n'
    '.sdb-item{text-align:center}\n'
    '.sdb-val{font-size:1.1rem;font-weight:900;color:var(--gr)}\n'
    '.sdb-lbl{font-size:9px;color:var(--mt);text-transform:uppercase;letter-spacing:.4px;font-weight:700}\n'
    '</style>\n'
    '</head>\n'
    '<body>\n'
    '\n'
    '<!-- SPLASH -->\n'
    '<div id="splash">\n'
    '  <div id="splash-particles"></div>\n'
    '  <div class="splash-logo">B</div>\n'
    '  <div class="splash-title">Bettor <em>AI</em></div>\n'
    '  <div class="splash-sub" id="spl-sub">Initializing&nbsp;&middot;&nbsp;Loading your data&hellip;</div>\n'
    '  <div class="splash-stages">\n'
    '    <div class="spl-stage" id="sst-db"><div class="spl-stage-icon">&#9679;</div><span class="spl-stage-lbl">Connecting to database</span><span class="spl-stage-val" id="sst-db-val"></span></div>\n'
    '    <div class="spl-stage" id="sst-games"><div class="spl-stage-icon">&#9679;</div><span class="spl-stage-lbl">Loading today\'s games</span><span class="spl-stage-val" id="sst-games-val"></span></div>\n'
    '    <div class="spl-stage" id="sst-bets"><div class="spl-stage-icon">&#9679;</div><span class="spl-stage-lbl">Restoring cached picks</span><span class="spl-stage-val" id="sst-bets-val"></span></div>\n'
    '    <div class="spl-stage" id="sst-ready"><div class="spl-stage-icon">&#9679;</div><span class="spl-stage-lbl">Preparing dashboard</span><span class="spl-stage-val" id="sst-ready-val"></span></div>\n'
    '  </div>\n'
    '  <div class="splash-bar-wrap">\n'
    '    <div class="splash-bar-track"><div class="splash-bar-fill" id="spl-bar"></div></div>\n'
    '    <div class="splash-pct" id="spl-pct">0%</div>\n'
    '  </div>\n'
    '  <div class="splash-db-strip" id="spl-db-strip" style="display:none">\n'
    '    <div class="sdb-item"><div class="sdb-val" id="sdb-games">&#8212;</div><div class="sdb-lbl">Games</div></div>\n'
    '    <div class="sdb-item"><div class="sdb-val" id="sdb-bets">&#8212;</div><div class="sdb-lbl">Picks</div></div>\n'
    '    <div class="sdb-item"><div class="sdb-val" id="sdb-updated">&#8212;</div><div class="sdb-lbl">Updated</div></div>\n'
    '  </div>\n'
    '</div>\n'
    '\n'
    '<!-- MAIN APP -->\n'
    '<div class="page" id="main-app" style="opacity:0;transition:opacity .5s ease">\n'
    '\n'
    '<!-- HEADER -->\n'
    '<div class="hdr">\n'
    '  <div class="brand">\n'
    '    <div class="logo">B</div>\n'
    '    <div class="brand-text">\n'
    '      <h1>Bettor <em>AI</em></h1>\n'
    '      <p id="lu">{% if state.last_updated %}Last updated {{ state.last_updated }}{% else %}Run analysis to get today\'s predictions{% endif %}</p>\n'
    '    </div>\n'
    '  </div>\n'
    '  <div class="hdr-right">\n'
    '    <div class="status-pill {{ state.status }}" id="spill"><div class="sdot {{ state.status }}" id="sdot"></div><span id="stxt">{{ state.status|capitalize }}</span></div>\n'
    '    <button class="console-btn" onclick="toggleConsole()">&#128203; Console</button>\n'
    '    <button class="run-btn" id="run-btn" onclick="runAnalysis()" {% if state.status==\'running\' %}disabled{% endif %}>&#9889; Run Analysis</button>\n'
    '  </div>\n'
    '</div>\n'
    '\n'
    '<!-- PROGRESS -->\n'
    '<div class="prog-wrap {% if state.status==\'running\' %}on{% endif %}" id="prog-wrap">\n'
    '  <div class="prog-head"><span id="pname">{{ state.phase }}</span><span id="ppct">{{ ((state.phase_idx / state.phase_total) * 100)|int }}%</span></div>\n'
    '  <div class="prog-track"><div class="prog-fill" id="pfill" style="width:{{ ((state.phase_idx / state.phase_total) * 100)|int }}%"></div></div>\n'
    '  <div class="phase-chips">\n'
    '    {% set labels=["MLB","Soccer","Stats","Injuries","Odds","Win Algo","Props","Cards","Save"] %}\n'
    '    {% for l in labels %}<div class="pchip {% if loop.index0 < state.phase_idx %}done{% elif loop.index0 == state.phase_idx %}act{% endif %}">{{ l }}</div>{% endfor %}\n'
    '  </div>\n'
    '</div>\n'
    '\n'
    '{% if state.status == \'error\' %}<div class="err-box">{{ state.error }}</div>{% endif %}\n'
    '\n'
    '<!-- TABS -->\n'
    '<div class="tabs">\n'
    '  <button class="tab act" onclick="showTab(\'today\',this)">&#128197; Today <span class="tab-cnt">{{ state.game_cards_today|length }}</span></button>\n'
    '  <button class="tab" onclick="showTab(\'tomorrow\',this)">&#127749; Tomorrow <span class="tab-cnt">{{ state.game_cards_tomorrow|length }}</span></button>\n'
    '  <button class="tab" onclick="showTab(\'parlay\',this)">&#128279; Top Parlay <span class="tab-cnt">{{ state.best_parlays|length }}</span></button>\n'
    '</div>\n'
    '\n'
    '<!-- GAME CARD MACRO -->\n'
    '{% macro game_card(c) %}\n'
    '<div class="game-card {{ c.overall_safety_label }}{% if c.when_label == \'LIVE\' %} LIVE-GAME{% endif %}">\n'
    '  {% if c.when_label == \'LIVE\' %}<div class="live-banner">&#128308;&nbsp;&nbsp;LIVE NOW</div>{% endif %}\n'
    '  <div class="gc-hdr">\n'
    '    <div class="gc-hdr-left">\n'
    '      <div class="gc-meta">\n'
    '        <span class="sport-chip {{ c.sport }}">{{ c.sport }}</span>\n'
    '        {% if c.league and c.league != c.sport %}<span style="font-size:9px;color:var(--mt)">{{ c.league }}</span>{% endif %}\n'
    '        <span class="wbadge {{ c.when_label }}">{{ c.when }}</span>\n'
    '      </div>\n'
    '      <div class="gc-matchup"><span class="gc-away">{{ c.away_team }}</span><span class="gc-sep">@</span><span class="gc-home">{{ c.home_team }}</span></div>\n'
    '      {% if c.sport == \'MLB\' and (c.home_starter or c.away_starter) %}<div class="gc-starter">&#9918; <span>{{ c.away_starter or \'TBD\' }}</span> vs <span>{{ c.home_starter or \'TBD\' }}</span></div>{% endif %}\n'
    '    </div>\n'
    '    <span class="sbadge {{ c.overall_safety_label }}">{{ c.overall_safety_label }}</span>\n'
    '  </div>\n'
    '  <div class="gc-rows">\n'
    '    {# WIN ROW #}\n'
    '    {% if c.win_pick %}{% set wp = c.win_pick %}\n'
    '    <div class="gc-row">\n'
    '      <span class="gc-type WIN">WIN</span>\n'
    '      <div class="gc-content">\n'
    '        <div class="gc-label">{{ wp.pick_team }}</div>\n'
    '        <div class="gc-sublabel">vs {{ wp.opp_team }}</div>\n'
    '        <div class="gc-bar WIN" style="width:{{ wp.conf }}%"></div>\n'
    '      </div>\n'
    '      <div class="gc-right">\n'
    '        <div class="gc-conf {{ wp.safety_label }}">{{ wp.conf }}%</div>\n'
    '        {% if wp.odds_str and wp.odds_str != \'N/A\' %}<div class="gc-odds">{{ wp.odds_str }}</div>{% endif %}\n'
    '      </div>\n'
    '    </div>\n'
    '    {% else %}\n'
    '    <div class="gc-row" style="opacity:.3"><span class="gc-type NONE">WIN</span><div class="gc-content"><div class="gc-label" style="color:var(--mt)">No odds available</div></div></div>\n'
    '    {% endif %}\n'
    '    {# PLAYER PROP ROW #}\n'
    '    {% if c.player_prop %}{% set pp = c.player_prop %}\n'
    '    <div class="gc-row">\n'
    '      <span class="gc-type PROP">PROP</span>\n'
    '      <div class="gc-content">\n'
    '        <div class="gc-label">{{ pp.name }} {{ pp.direction }} {{ pp.line }} {{ pp.prop_label }}</div>\n'
    '        <div class="gc-sublabel">{{ pp.team }}</div>\n'
    '        <div class="gc-bar PROP" style="width:{{ pp.conf }}%"></div>\n'
    '      </div>\n'
    '      <div class="gc-right">\n'
    '        <div class="gc-conf {{ pp.safety_label }}">{{ pp.conf }}%</div>\n'
    '        <div class="gc-odds" style="color:{% if pp.direction == \'OVER\' %}#22c55e{% else %}#ef4444{% endif %}">{{ pp.direction }}</div>\n'
    '      </div>\n'
    '    </div>\n'
    '    {% else %}\n'
    '    <div class="gc-row" style="opacity:.3"><span class="gc-type NONE">PROP</span><div class="gc-content"><div class="gc-label" style="color:var(--mt)">No prop available</div></div></div>\n'
    '    {% endif %}\n'
    '    {# GAME PROP ROW #}\n'
    '    {% if c.game_prop %}{% set gp = c.game_prop %}\n'
    '    <div class="gc-row">\n'
    '      <span class="gc-type GAME">GAME</span>\n'
    '      <div class="gc-content">\n'
    '        <div class="gc-label">{{ gp.label }}</div>\n'
    '        <div class="gc-sublabel">{% if c.sport == \'SOCCER\' %}Both teams to score{% else %}Game total{% endif %}</div>\n'
    '        <div class="gc-bar GAME" style="width:{{ gp.conf }}%"></div>\n'
    '      </div>\n'
    '      <div class="gc-right">\n'
    '        <div class="gc-conf {{ gp.safety_label }}">{{ gp.conf }}%</div>\n'
    '      </div>\n'
    '    </div>\n'
    '    {% else %}\n'
    '    <div class="gc-row" style="opacity:.3"><span class="gc-type NONE">GAME</span><div class="gc-content"><div class="gc-label" style="color:var(--mt)">No game prop</div></div></div>\n'
    '    {% endif %}\n'
    '  </div>\n'
    '</div>\n'
    '{% endmacro %}\n'
    '\n'
    '<!-- TODAY TAB -->\n'
    '<div class="tab-panel on" id="tab-today">\n'
    '  {% if state.status == \'running\' %}\n'
    '  <div class="game-grid">{% for _ in range(4) %}<div class="sk-card"><div class="sk" style="height:12px;width:45%;margin-bottom:14px"></div><div class="sk" style="height:20px;width:90%;margin-bottom:10px"></div><div class="sk" style="height:14px;width:70%;margin-bottom:8px"></div><div class="sk" style="height:14px;width:80%"></div></div>{% endfor %}</div>\n'
    '  {% elif state.game_cards_today %}\n'
    '  <div class="game-grid">{% for c in state.game_cards_today %}{{ game_card(c) }}{% endfor %}</div>\n'
    '  {% else %}\n'
    '  <div class="empty"><span class="empty-icon">&#128197;</span><strong>No picks for today yet</strong><p>Click <strong>Run Analysis</strong> to fetch today\'s games.</p></div>\n'
    '  {% endif %}\n'
    '</div>\n'
    '\n'
    '<!-- TOMORROW TAB -->\n'
    '<div class="tab-panel" id="tab-tomorrow">\n'
    '  {% if state.status == \'running\' %}\n'
    '  <div class="game-grid">{% for _ in range(3) %}<div class="sk-card"><div class="sk" style="height:12px;width:45%;margin-bottom:14px"></div><div class="sk" style="height:20px;width:90%;margin-bottom:10px"></div><div class="sk" style="height:14px;width:70%;margin-bottom:8px"></div><div class="sk" style="height:14px;width:80%"></div></div>{% endfor %}</div>\n'
    '  {% elif state.game_cards_tomorrow %}\n'
    '  <div class="game-grid">{% for c in state.game_cards_tomorrow %}{{ game_card(c) }}{% endfor %}</div>\n'
    '  {% else %}\n'
    '  <div class="empty"><span class="empty-icon">&#127749;</span><strong>No picks for tomorrow yet</strong><p>Run analysis to see tomorrow\'s game predictions.</p></div>\n'
    '  {% endif %}\n'
    '</div>\n'
    '\n'
    '<!-- PARLAY TAB -->\n'
    '<div class="tab-panel" id="tab-parlay">\n'
    '  {% if state.best_parlays %}\n'
    '  <div class="parlay-header">\n'
    '    <h2>&#128279; Safest Parlays</h2>\n'
    '    <span class="parlay-subtext">Ranked by safety score &middot; One pick per game</span>\n'
    '  </div>\n'
    '  <div class="parlay-grid">\n'
    '    {% for parl in state.best_parlays %}\n'
    '    <div class="parl-card {{ parl.safety_label }}{% if loop.index0 == 0 %} top-pick{% endif %}">\n'
    '      <div class="parl-hdr">\n'
    '        <span class="parl-n-badge">{{ parl.n_legs }}-LEG PARLAY</span>\n'
    '        <span class="sbadge {{ parl.safety_label }}">{{ parl.safety_label }}</span>\n'
    '        {% if loop.index0 == 0 %}<span class="parl-rec-badge">&#11088; TOP PICK</span>{% endif %}\n'
    '      </div>\n'
    '      <div class="parl-stats">\n'
    '        <div class="pstat">Prob <span class="gr">{{ parl.combined_prob }}%</span></div>\n'
    '        <div class="pstat">Payout <span class="pu">{{ parl.combined_dec }}x</span></div>\n'
    '        <div class="pstat">Safety <span class="yw">{{ (parl.avg_safety * 100)|round|int }}%</span></div>\n'
    '      </div>\n'
    '      <div class="parl-legs">\n'
    '        {% for leg in parl.legs %}\n'
    '        <div class="parl-leg-item">\n'
    '          <div class="parl-leg-num">{{ loop.index }}</div>\n'
    '          <div class="parl-leg-label">{{ leg.label }}</div>\n'
    '          <span class="sbadge-sm {{ leg.badge }}">{{ leg.badge }}</span>\n'
    '          <div class="parl-leg-conf">{{ leg.conf }}%</div>\n'
    '        </div>\n'
    '        {% endfor %}\n'
    '      </div>\n'
    '    </div>\n'
    '    {% endfor %}\n'
    '  </div>\n'
    '  {% elif state.status == \'running\' %}\n'
    '  <div class="parlay-grid">{% for _ in range(3) %}<div class="sk-card"><div class="sk" style="height:16px;width:50%;margin-bottom:12px"></div><div class="sk" style="height:12px;width:80%;margin-bottom:8px"></div><div class="sk" style="height:10px;width:90%;margin-bottom:6px"></div><div class="sk" style="height:10px;width:85%"></div></div>{% endfor %}</div>\n'
    '  {% else %}\n'
    '  <div class="empty"><span class="empty-icon">&#128279;</span><strong>No parlays yet</strong><p>Run analysis to generate the safest 2&ndash;10 leg parlays.</p></div>\n'
    '  {% endif %}\n'
    '</div>\n'
    '\n'
    '</div><!-- /main-app -->\n'
    '\n'
    '<!-- CONSOLE -->\n'
    '<div class="console-wrap" id="console-wrap">\n'
    '  <div class="console-pull" onclick="toggleConsole()">\n'
    '    <div class="cpull-l"><div class="cpull-dot" id="cdot"></div><span>&#9654; Console Log</span><span class="cpull-badge" id="ccount">0 lines</span></div>\n'
    '    <span style="font-size:10px;color:var(--mt)" id="ctog">&#9662; Show</span>\n'
    '  </div>\n'
    '  <div class="console-body" id="console-body"><div id="clines"><div class="lg-empty">No logs yet.</div></div></div>\n'
    '</div>\n'
    '\n'
    '<script>\n'
    'const STATUS = "{{ state.status }}";\n'
    '\n'
    'function showTab(id, btn) {\n'
    '  document.querySelectorAll(\'.tab\').forEach(t => t.classList.remove(\'act\'));\n'
    '  document.querySelectorAll(\'.tab-panel\').forEach(p => p.classList.remove(\'on\'));\n'
    '  btn.classList.add(\'act\');\n'
    '  document.getElementById(\'tab-\' + id).classList.add(\'on\');\n'
    '}\n'
    '\n'
    'async function runAnalysis() {\n'
    '  const btn = document.getElementById(\'run-btn\');\n'
    '  btn.disabled = true;\n'
    '  try {\n'
    '    const r = await fetch(\'/api/run\', {method:\'POST\'});\n'
    '    if (!r.ok) { const d = await r.json(); alert(d.msg || \'Error\'); btn.disabled = false; return; }\n'
    '    setStatus(\'running\');\n'
    '    startPolling();\n'
    '  } catch(e) { alert(\'Network error\'); btn.disabled = false; }\n'
    '}\n'
    '\n'
    'let _pt = null, _logOff = 0;\n'
    'function startPolling() {\n'
    '  if (_pt) clearInterval(_pt);\n'
    '  _pt = setInterval(async () => {\n'
    '    try {\n'
    '      const [sr, lr] = await Promise.all([\n'
    '        fetch(\'/api/status\').then(r => r.json()),\n'
    '        fetch(\'/api/logs?since=\' + _logOff).then(r => r.json()),\n'
    '      ]);\n'
    '      updateStatus(sr);\n'
    '      appendLogs(lr);\n'
    '      if (sr.status === \'done\' || sr.status === \'error\') {\n'
    '        clearInterval(_pt);\n'
    '        if (sr.status === \'done\') setTimeout(() => location.reload(), 1200);\n'
    '      }\n'
    '    } catch(_) {}\n'
    '  }, 1800);\n'
    '}\n'
    '\n'
    'function updateStatus(s) {\n'
    '  setStatus(s.status);\n'
    '  document.getElementById(\'pname\').textContent = s.phase || \'\';\n'
    '  document.getElementById(\'ppct\').textContent  = Math.round((s.phase_idx / s.phase_total) * 100) + \'%\';\n'
    '  document.getElementById(\'pfill\').style.width = Math.round((s.phase_idx / s.phase_total) * 100) + \'%\';\n'
    '  document.querySelectorAll(\'.pchip\').forEach((c, i) => {\n'
    '    c.classList.toggle(\'done\', i < s.phase_idx);\n'
    '    c.classList.toggle(\'act\',  i === s.phase_idx);\n'
    '  });\n'
    '  const pw = document.getElementById(\'prog-wrap\');\n'
    '  if (s.status === \'running\') pw.classList.add(\'on\'); else pw.classList.remove(\'on\');\n'
    '}\n'
    '\n'
    'function setStatus(st) {\n'
    '  const pill = document.getElementById(\'spill\');\n'
    '  const dot  = document.getElementById(\'sdot\');\n'
    '  pill.className = \'status-pill \' + st;\n'
    '  dot.className  = \'sdot \' + st;\n'
    '  document.getElementById(\'stxt\').textContent = st.charAt(0).toUpperCase() + st.slice(1);\n'
    '  document.getElementById(\'run-btn\').disabled = st === \'running\';\n'
    '  document.getElementById(\'cdot\').classList.toggle(\'act\', st === \'running\');\n'
    '}\n'
    '\n'
    'function toggleConsole() {\n'
    '  const w = document.getElementById(\'console-wrap\');\n'
    '  const tog = document.getElementById(\'ctog\');\n'
    '  const open = w.classList.toggle(\'open\');\n'
    '  tog.textContent = open ? \'\\u25b4 Hide\' : \'\\u25be Show\';\n'
    '}\n'
    '\n'
    'function appendLogs(data) {\n'
    '  if (!data.logs || !data.logs.length) return;\n'
    '  const box = document.getElementById(\'clines\');\n'
    '  if (box.querySelector(\'.lg-empty\')) box.innerHTML = \'\';\n'
    '  data.logs.forEach(l => {\n'
    '    const d = document.createElement(\'div\');\n'
    '    d.className = \'lg\' + (l.includes(\'ERROR\') ? \' err\' : l.includes(\'WARNING\') ? \' warn\' :\n'
    '                          l.includes(\'===\') ? \' phase\' : l.includes(\'\\u2713\') ? \' ok\' : \'\');\n'
    '    const m = l.match(/^\\[(\\d+:\\d+:\\d+)\\]\\s(.*)$/);\n'
    '    d.innerHTML = m ? \'<span class="ts">\'+m[1]+\'</span><span class="msg">\'+m[2]+\'</span>\'\n'
    '                    : \'<span class="msg">\'+l+\'</span>\';\n'
    '    box.appendChild(d);\n'
    '  });\n'
    '  _logOff = data.total;\n'
    '  document.getElementById(\'ccount\').textContent = data.total + \' lines\';\n'
    '  const body = document.getElementById(\'console-body\');\n'
    '  body.scrollTop = body.scrollHeight;\n'
    '}\n'
    '\n'
    '(async function initSplash() {\n'
    '  const stages = [\'sst-db\',\'sst-games\',\'sst-bets\',\'sst-ready\'];\n'
    '  const bar = document.getElementById(\'spl-bar\');\n'
    '  const pct = document.getElementById(\'spl-pct\');\n'
    '  const sub = document.getElementById(\'spl-sub\');\n'
    '  const pf  = document.getElementById(\'splash-particles\');\n'
    '  for (let i = 0; i < 22; i++) {\n'
    '    const d = document.createElement(\'div\'); d.className = \'sp-dot\';\n'
    '    const sz = Math.random() * 4 + 2;\n'
    '    d.style.cssText = \'left:\'+Math.random()*100+\'%;top:\'+(80+Math.random()*30)+\'%;\'+\n'
    '      \'width:\'+sz+\'px;height:\'+sz+\'px;\'+\n'
    '      \'background:\'+[\'#22c55e\',\'#0d9488\',\'#3b82f6\',\'#a855f7\'][i%4]+\';\'+\n'
    '      \'animation-duration:\'+(5+Math.random()*8)+\'s;animation-delay:\'+Math.random()*4+\'s\';\n'
    '    pf.appendChild(d);\n'
    '  }\n'
    '  function setStage(i, val) {\n'
    '    stages.forEach((id, j) => {\n'
    '      const el = document.getElementById(id);\n'
    '      if (j < i) el.className = \'spl-stage done\';\n'
    '      else if (j === i) el.className = \'spl-stage act\';\n'
    '      else el.className = \'spl-stage\';\n'
    '    });\n'
    '    const p = Math.round((i / stages.length) * 100);\n'
    '    bar.style.width = p + \'%\'; pct.textContent = p + \'%\';\n'
    '    if (val !== undefined) { const v = document.getElementById(stages[i]+\'-val\'); if(v) v.textContent = val; }\n'
    '  }\n'
    '  try {\n'
    '    setStage(0);\n'
    '    sub.textContent = \'Connecting to database\\u2026\';\n'
    '    const data = await fetch(\'/api/cached-state\').then(r => r.json());\n'
    '    setStage(1, \'\\u2713\');\n'
    '    sub.textContent = "Loading today\'s games\\u2026";\n'
    '    await new Promise(r => setTimeout(r, 300));\n'
    '    setStage(2, data.db_stats?.total_games ? data.db_stats.total_games+\' games\' : \'\');\n'
    '    sub.textContent = \'Restoring cached picks\\u2026\';\n'
    '    await new Promise(r => setTimeout(r, 300));\n'
    '    const tp = (data.db_stats?.total_bets||0)+(data.db_stats?.total_props||0);\n'
    '    setStage(3, tp ? tp+\' picks\' : \'\');\n'
    '    if (data.has_cache) {\n'
    '      const strip = document.getElementById(\'spl-db-strip\');\n'
    '      document.getElementById(\'sdb-games\').textContent   = data.db_stats?.total_games || \'\\u2014\';\n'
    '      document.getElementById(\'sdb-bets\').textContent    = tp || \'\\u2014\';\n'
    '      document.getElementById(\'sdb-updated\').textContent = data.last_updated\n'
    '        ? data.last_updated.replace(/\\d{4}-\\d{2}-\\d{2}\\s/,\'\') : \'\\u2014\';\n'
    '      strip.style.display = \'flex\';\n'
    '    }\n'
    '    sub.textContent = \'Ready\';\n'
    '    bar.style.width = \'100%\'; pct.textContent = \'100%\';\n'
    '    await new Promise(r => setTimeout(r, 500));\n'
    '  } catch(_) { bar.style.width = \'100%\'; }\n'
    '  document.getElementById(\'splash\').classList.add(\'hidden\');\n'
    '  document.getElementById(\'main-app\').style.opacity = \'1\';\n'
    '  if (STATUS === \'running\') startPolling();\n'
    '})();\n'
    '</script>\n'
    '</body>\n'
    '</html>\n'
)

OUT.write_text(HTML, encoding="utf-8")
print(f"Written {HTML.count(chr(10))} lines to {OUT}")
