"""Downloadable PDF strategy report for the Alpaca crypto bot -- "what the
strategy is and how it's going" as a document a person can save, not just
a dashboard someone has to screenshot. Same fpdf2 pattern and
account/trade-history sections as app_kalshi.py's own perps_report.py,
extended with what this ask specifically wanted beyond that original:
current strategy configuration, a walk-forward backtest summary, and a
real trade-lesson analysis ("what the bot is learning from its losses").

Same DEMO/LIVE distinction perps_report.py already established (mode
label) -- this account reads DEMO/PAPER today (ALPACA_TRADING_BASE_URL
points at Alpaca's paper endpoint) and will read LIVE automatically the
day that flips to the real endpoint; no separate "real account report"
needed, it's the same report reading the same real account state either
way.

Best-effort in spirit but NOT best-effort in contract: unlike the
Threads-posting modules, a report the user explicitly clicked "download"
for should raise on a real failure (visible in the browser) rather than
silently return nothing.
"""
from __future__ import annotations

import datetime as dt
from typing import Any

_BRAND = (17, 24, 39)          # near-black header band
_ACCENT = (247, 147, 26)       # bitcoin orange -- matches this market's own Threads/chart accent color
_POSITIVE = (21, 128, 61)      # green -- gains
_NEGATIVE = (185, 28, 28)      # red -- losses
_MUTED = (107, 114, 128)       # gray -- captions/footers
_ROW_ALT = (243, 244, 246)     # light zebra-stripe

MAX_TRADES_IN_REPORT = 200

_PARAM_LABELS: dict[str, str] = {
    "position_size_pct": "Position size (% of available balance)",
    "max_concurrent_positions": "Max concurrent positions",
    "take_profit_pct": "Take-profit (flat default; adaptive per-coin)",
    "stop_loss_pct": "Stop-loss (flat default; adaptive per-coin)",
    "max_hold_minutes": "Max hold time (minutes)",
    "daily_loss_cap_pct": "Daily loss cap",
    "model_confidence_min": "Model confidence floor",
    "min_volume_z": "Min unusual-volume z-score",
    "min_volatility_ratio": "Min short/long volatility ratio",
    "taker_fee_rate": "Taker fee rate (per leg)",
}
_PARAM_PCT_KEYS = {"position_size_pct", "take_profit_pct", "stop_loss_pct", "daily_loss_cap_pct", "model_confidence_min", "taker_fee_rate"}


def _fmt_usd(value: float) -> str:
    return f"${value:,.2f}" if value >= 0 else f"-${abs(value):,.2f}"


def _fmt_param(key: str, value: Any) -> str:
    try:
        if key.startswith("min_") and float(value) <= -1e8:
            return "no filter"
    except (TypeError, ValueError):
        pass
    if key in _PARAM_PCT_KEYS:
        try:
            return f"{float(value):.2%}"
        except (TypeError, ValueError):
            return str(value)
    return str(value)


def _trade_stats(trade_log: list[dict[str, Any]]) -> dict[str, Any]:
    real_trades = [t for t in trade_log if not t.get("dry_run")]
    pnls = [float(t.get("realized_pnl_usd", 0.0)) for t in real_trades]
    wins = [p for p in pnls if p > 0]
    losses = [p for p in pnls if p < 0]
    return {
        "count": len(pnls),
        "win_count": len(wins),
        "loss_count": len(losses),
        "win_rate": (len(wins) / len(pnls) * 100.0) if pnls else 0.0,
        "avg_win": (sum(wins) / len(wins)) if wins else 0.0,
        "avg_loss": (sum(losses) / len(losses)) if losses else 0.0,
        "best_trade": max(pnls) if pnls else 0.0,
        "worst_trade": min(pnls) if pnls else 0.0,
        "total_fees": sum(float(t.get("fee_usd", 0.0)) for t in real_trades),
    }


def _make_pdf():
    from fpdf import FPDF

    class _ReportPDF(FPDF):
        """footer() is fpdf2's own per-page hook -- see perps_report.py's
        own identical comment for why this (not a manual set_y(-15) at the
        end of content) avoids a spurious extra blank page."""

        def footer(self) -> None:
            self.set_y(-15)
            self.set_font("Helvetica", "I", 8)
            self.set_text_color(*_MUTED)
            self.cell(0, 10, "Generated by the Alpaca Crypto bot -- figures reflect this account's own durable trade record.")

    return _ReportPDF(orientation="P", unit="mm", format="A4")


def generate_pdf_report(*, status: dict[str, Any], trade_batch: dict[str, Any]) -> bytes:
    """Builds the full report and returns raw PDF bytes. `status` is
    alpaca_crypto_server._crypto_status_snapshot()'s own return dict;
    `trade_batch` is alpaca_crypto_trade_analysis.analyze_recent_trade_batch()'s
    own return dict."""
    from fpdf import XPos, YPos

    trade_log = list(status.get("trade_log") or [])
    trade_log.sort(key=lambda t: t.get("closed_at", ""), reverse=True)
    stats = _trade_stats(trade_log)
    generated_at = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    is_demo = status.get("account_type") != "live" or not status.get("live_trading_enabled")
    mode_label = "PAPER / DEMO (no real money)" if is_demo else "LIVE (real money)"

    pdf = _make_pdf()
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.add_page()

    # --- Header band ---
    pdf.set_fill_color(*_BRAND)
    pdf.rect(0, 0, 210, 32, style="F")
    pdf.set_xy(12, 8)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 20)
    pdf.cell(0, 10, "Alpaca Crypto -- Strategy Report", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_x(12)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 6, f"Generated {generated_at}  |  Mode: {mode_label}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_text_color(0, 0, 0)
    pdf.set_y(40)

    def _section_title(title: str) -> None:
        pdf.set_font("Helvetica", "B", 13)
        pdf.set_text_color(*_ACCENT)
        pdf.cell(0, 8, title, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.set_text_color(0, 0, 0)
        pdf.ln(1)

    def _row(label: str, value: str, *, color: tuple[int, int, int] | None = None) -> None:
        pdf.set_font("Helvetica", "", 11)
        pdf.set_text_color(*_MUTED)
        pdf.cell(100, 7, label)
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(*(color or (0, 0, 0)))
        pdf.cell(0, 7, value, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.set_text_color(0, 0, 0)

    def _wrapped_note(text: str, *, color: tuple[int, int, int] = (0, 0, 0)) -> None:
        pdf.set_font("Helvetica", "", 9.5)
        pdf.set_text_color(*color)
        pdf.multi_cell(0, 5.5, text)
        pdf.set_text_color(0, 0, 0)
        pdf.ln(0.5)

    # --- Account Summary ---
    _section_title("Account Summary")
    _row("Current balance:", _fmt_usd(float(status.get("balance") or 0.0)))
    _row("Available balance:", _fmt_usd(float(status.get("available_balance") or 0.0)))
    total_pnl = float(status.get("total_realized_pnl_usd") or 0.0)
    today_pnl = float(status.get("today_realized_pnl_usd") or 0.0)
    _row("Total realized P&L (all time):", _fmt_usd(total_pnl), color=_POSITIVE if total_pnl >= 0 else _NEGATIVE)
    _row("Today's realized P&L:", _fmt_usd(today_pnl), color=_POSITIVE if today_pnl >= 0 else _NEGATIVE)
    _row(
        "Open positions right now:",
        f"{status.get('open_position_count', 0)} / {status.get('max_concurrent_positions', '?')} slots",
    )
    pdf.ln(3)

    # --- Strategy Configuration ---
    _section_title("Strategy Configuration")
    params = status.get("params") or {}
    for key, label in _PARAM_LABELS.items():
        if key in params:
            _row(label, _fmt_param(key, params[key]))
    pdf.ln(3)

    # --- Trade Performance ---
    _section_title("Trade Performance")
    _row("Total closed real trades:", str(stats["count"]))
    _row("Win rate:", f"{stats['win_rate']:.1f}%  ({stats['win_count']} win / {stats['loss_count']} loss)")
    _row("Average win:", _fmt_usd(stats["avg_win"]), color=_POSITIVE)
    _row("Average loss:", _fmt_usd(stats["avg_loss"]), color=_NEGATIVE)
    _row("Best single trade:", _fmt_usd(stats["best_trade"]), color=_POSITIVE)
    _row("Worst single trade:", _fmt_usd(stats["worst_trade"]), color=_NEGATIVE)
    _row("Total fees paid:", _fmt_usd(stats["total_fees"]))
    pdf.ln(3)

    # --- What The Bot Is Learning (loss-pattern analysis) ---
    _section_title("What The Bot Is Learning")
    if not trade_batch.get("trades_analyzed"):
        _wrapped_note("No closed real trades analyzed yet.", color=_MUTED)
    else:
        _wrapped_note(
            f"Last {trade_batch['trades_analyzed']} closed trades: {trade_batch['wins']} win / "
            f"{trade_batch['losses']} loss, total {_fmt_usd(trade_batch['total_pnl_usd'])}."
        )
        pdf.ln(1)
        for s in (trade_batch.get("snapshots") or [])[:15]:
            color = _POSITIVE if s.get("outcome") == "win" else _NEGATIVE if s.get("outcome") == "loss" else _MUTED
            _wrapped_note(f"- {s.get('lesson', '')}", color=color)
        recs = trade_batch.get("recommendations") or []
        if recs:
            pdf.ln(1)
            pdf.set_font("Helvetica", "B", 10.5)
            pdf.cell(0, 6, "Recurring patterns worth acting on:", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            for r in recs:
                _wrapped_note(f"- {r}")
    pdf.ln(2)

    # --- Walk-Forward Backtest (multiple time-frame folds) ---
    _section_title("Walk-Forward Backtest (Multiple Time-Frame Folds)")
    walkforward = status.get("latest_walkforward") or {}
    if not walkforward.get("ok"):
        _wrapped_note(
            "No walk-forward backtest has completed yet -- check back after the next scheduled run.", color=_MUTED,
        )
    else:
        _row("Folds tested:", str(walkforward.get("fold_count", "n/a")))
        _row(
            "Profitable folds:",
            f"{walkforward.get('profitable_fold_count', 'n/a')} / {walkforward.get('fold_count', 'n/a')}",
        )
        mean_ret = walkforward.get("mean_return_pct")
        _row(
            "Mean return per fold:", f"{mean_ret:.2%}" if isinstance(mean_ret, (int, float)) else "n/a",
            color=_POSITIVE if isinstance(mean_ret, (int, float)) and mean_ret >= 0 else _NEGATIVE,
        )
        std_ret = walkforward.get("std_return_pct")
        _row("Return std deviation:", f"{std_ret:.2%}" if isinstance(std_ret, (int, float)) else "n/a")
        folds = walkforward.get("folds") or []
        if folds:
            pdf.ln(1)
            col_widths = (18, 28, 28, 28, 40)
            headers = ("Fold", "Return", "Trades", "Win rate", "Model")
            pdf.set_font("Helvetica", "B", 8.5)
            pdf.set_fill_color(*_BRAND)
            pdf.set_text_color(255, 255, 255)
            for w, h in zip(col_widths, headers):
                pdf.cell(w, 7, h, border=0, fill=True)
            pdf.ln(7)
            pdf.set_text_color(0, 0, 0)
            for i, f in enumerate(folds):
                ret = f.get("return_pct")
                pdf.set_font("Helvetica", "", 8)
                pdf.set_fill_color(*_ROW_ALT)
                fill = i % 2 == 1
                pdf.cell(col_widths[0], 6, str(i + 1), fill=fill)
                pdf.set_text_color(*(_POSITIVE if isinstance(ret, (int, float)) and ret >= 0 else _NEGATIVE))
                pdf.cell(col_widths[1], 6, f"{ret:.2%}" if isinstance(ret, (int, float)) else "n/a", fill=fill)
                pdf.set_text_color(0, 0, 0)
                pdf.cell(col_widths[2], 6, str(f.get("trade_count", "n/a")), fill=fill)
                win_rate = f.get("win_rate")
                pdf.cell(col_widths[3], 6, f"{win_rate:.1%}" if isinstance(win_rate, (int, float)) else "n/a", fill=fill)
                pdf.cell(col_widths[4], 6, str(f.get("model_used") or "n/a"), fill=fill)
                pdf.ln(6)
    pdf.ln(3)

    # --- Trade History table ---
    _section_title("Trade History")
    shown = trade_log[:MAX_TRADES_IN_REPORT]
    if len(trade_log) > MAX_TRADES_IN_REPORT:
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(*_MUTED)
        pdf.cell(0, 6, f"(most recent {MAX_TRADES_IN_REPORT} of {len(trade_log)})", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.set_text_color(0, 0, 0)

    if not shown:
        pdf.set_font("Helvetica", "", 11)
        pdf.set_text_color(*_MUTED)
        pdf.cell(0, 8, "No closed trades yet.", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.set_text_color(0, 0, 0)
    else:
        col_widths = (28, 22, 22, 22, 24, 24, 46)
        headers = ("Closed", "Symbol", "Entry", "Exit", "P&L", "Fee", "Reason")
        pdf.set_font("Helvetica", "B", 8.5)
        pdf.set_fill_color(*_BRAND)
        pdf.set_text_color(255, 255, 255)
        for w, h in zip(col_widths, headers):
            pdf.cell(w, 7, h, border=0, fill=True)
        pdf.ln(7)
        pdf.set_text_color(0, 0, 0)

        for i, t in enumerate(shown):
            if pdf.get_y() > 275:
                pdf.add_page()
            pnl = float(t.get("realized_pnl_usd", 0.0))
            closed_at = str(t.get("closed_at", ""))[:16].replace("T", " ")
            reason = str(t.get("reason", ""))[:32]
            pdf.set_font("Helvetica", "", 8)
            pdf.set_fill_color(*_ROW_ALT)
            fill = i % 2 == 1
            pdf.cell(col_widths[0], 6, closed_at, fill=fill)
            pdf.cell(col_widths[1], 6, str(t.get("symbol", ""))[:14], fill=fill)
            pdf.cell(col_widths[2], 6, f"{float(t.get('entry_price', 0.0)):.4f}", fill=fill)
            pdf.cell(col_widths[3], 6, f"{float(t.get('exit_price', 0.0)):.4f}", fill=fill)
            pdf.set_text_color(*(_POSITIVE if pnl >= 0 else _NEGATIVE))
            pdf.cell(col_widths[4], 6, _fmt_usd(pnl), fill=fill)
            pdf.set_text_color(0, 0, 0)
            pdf.cell(col_widths[5], 6, _fmt_usd(float(t.get("fee_usd", 0.0))), fill=fill)
            pdf.cell(col_widths[6], 6, reason, fill=fill)
            pdf.ln(6)

    return bytes(pdf.output())
