"""Downloadable PDF account report for the Kalshi Perps live-money bot --
"what has the live account actually made" as a document a person can save,
not just a JSON blob on a dashboard. Pulls from the exact same durable
state (trade_log, realized_pnl_by_date) and real account balance every
other reporting surface here already uses, so the numbers always match
what /api/status shows.

fpdf2, not weasyprint/reportlab's heavier paths: pure Python, no external
binary dependency, light enough to generate on-demand inside this same
512Mi process -- same "manage memory weight deliberately" discipline
already proven necessary elsewhere in this codebase (see
chart_snapshot.py's own docstring).

Best-effort in spirit but NOT best-effort in contract: unlike the
Threads-posting modules, a report the user explicitly clicked "download"
for should raise on a real failure (visible in the browser) rather than
silently return nothing -- there's no background job here to protect from
a raised exception the way trading logic needs protecting.
"""
from __future__ import annotations

import datetime as dt
import logging
from typing import Any

logger = logging.getLogger(__name__)

_BRAND = (17, 24, 39)          # near-black header band
_ACCENT = (37, 99, 235)        # blue -- headings/section rules
_POSITIVE = (21, 128, 61)      # green -- gains
_NEGATIVE = (185, 28, 28)      # red -- losses
_MUTED = (107, 114, 128)       # gray -- captions/footers
_ROW_ALT = (243, 244, 246)     # light zebra-stripe

MAX_TRADES_IN_REPORT = 200


def _fmt_usd(value: float) -> str:
    return f"${value:,.2f}" if value >= 0 else f"-${abs(value):,.2f}"


def _trade_stats(trade_log: list[dict[str, Any]]) -> dict[str, Any]:
    """Win/loss/avg/best/worst are computed over exit_kind == "full" rows
    only -- a "partial" row (perps' USE_PARTIAL_EXIT, selling only part of
    a still-open position) is real P&L but not a resolved trade outcome,
    same exclusion server_common.win_rate_stats applies to this same
    trade_log. total_fees still sums EVERY row (a partial exit pays a real
    fee too). Rows without the field (predating this, or a non-perps trade
    log) default to "full" so nothing regresses."""
    resolved = [t for t in trade_log if t.get("exit_kind", "full") == "full"]
    pnls = [float(t.get("realized_pnl_usd", 0.0)) for t in resolved]
    wins = [p for p in pnls if p > 0]
    losses = [p for p in pnls if p < 0]
    return {
        "count": len(pnls),
        "win_count": len(wins),
        "loss_count": len(losses),
        "win_rate": (len(wins) / len(pnls) * 100.0) if pnls else 0.0,
        "avg_win": (sum(wins) / len(wins)) if wins else 0.0,
        "avg_loss": (sum(losses) / len(losses)) if losses else 0.0,
        "best_trade": max(pnls) if pnls else 0.0,
        "worst_trade": min(pnls) if pnls else 0.0,
        "total_fees": sum(float(t.get("fee_usd", 0.0)) for t in trade_log),
    }


def _make_pdf():
    from fpdf import FPDF

    class _ReportPDF(FPDF):
        """footer() is fpdf2's own per-page hook -- called automatically
        at the bottom margin of EVERY page (including ones added by
        auto-page-break) instead of a manual set_y(-15) at the end of
        content, which triggered a spurious extra blank page here: -15
        from the bottom landed inside the auto-page-break trigger margin,
        so fpdf2 started a new page before the footer text ever
        rendered, leaving it duplicated onto that unwanted second page."""

        def footer(self) -> None:
            self.set_y(-15)
            self.set_font("Helvetica", "I", 8)
            self.set_text_color(*_MUTED)
            self.cell(0, 10, "Generated by the Kalshi Perps bot -- figures reflect this account's own durable trade record.")

    return _ReportPDF(orientation="P", unit="mm", format="A4")


def generate_pdf_report(
    *, state: dict[str, Any], account_balance_usd: float | None, live_trading_enabled: bool,
) -> bytes:
    """Builds the full report and returns raw PDF bytes (callers write
    these straight to an HTTP response -- no temp file needed, fpdf2
    outputs entirely in memory)."""
    from fpdf import XPos, YPos

    trade_log = list(state.get("trade_log") or [])
    trade_log.sort(key=lambda t: t.get("closed_at", ""), reverse=True)
    realized_pnl_by_date = state.get("realized_pnl_by_date") or {}
    total_realized_pnl = round(sum(float(v) for v in realized_pnl_by_date.values()), 2)
    today_str = dt.datetime.now(dt.timezone.utc).date().isoformat()
    today_pnl = round(float(realized_pnl_by_date.get(today_str, 0.0)), 2)
    stats = _trade_stats(trade_log)
    generated_at = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    pdf = _make_pdf()
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.add_page()

    # --- Header band ---
    pdf.set_fill_color(*_BRAND)
    pdf.rect(0, 0, 210, 32, style="F")
    pdf.set_xy(12, 8)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 20)
    pdf.cell(0, 10, "Kalshi Perps -- Live Account Report", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_x(12)
    pdf.set_font("Helvetica", "", 10)
    mode_label = "LIVE (real money)" if live_trading_enabled else "PAPER / SIMULATED"
    pdf.cell(0, 6, f"Generated {generated_at}  |  Mode: {mode_label}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_text_color(0, 0, 0)
    pdf.set_y(40)

    # --- Summary cards ---
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(*_ACCENT)
    pdf.cell(0, 8, "Account Summary", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(1)

    def _summary_row(label: str, value: str, *, color: tuple[int, int, int] | None = None) -> None:
        pdf.set_font("Helvetica", "", 11)
        pdf.set_text_color(*_MUTED)
        pdf.cell(70, 7, label)
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(*(color or (0, 0, 0)))
        pdf.cell(0, 7, value, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.set_text_color(0, 0, 0)

    if account_balance_usd is not None:
        _summary_row("Current available balance:", _fmt_usd(account_balance_usd))
    _summary_row(
        "Total realized P&L (all time):", _fmt_usd(total_realized_pnl),
        color=_POSITIVE if total_realized_pnl >= 0 else _NEGATIVE,
    )
    _summary_row(
        "Today's realized P&L:", _fmt_usd(today_pnl),
        color=_POSITIVE if today_pnl >= 0 else _NEGATIVE,
    )
    _summary_row("Open positions right now:", str(len(state.get("positions") or [])))
    pdf.ln(3)

    # --- Trade performance ---
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(*_ACCENT)
    pdf.cell(0, 8, "Trade Performance", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(1)
    _summary_row("Total closed trades:", str(stats["count"]))
    _summary_row(
        "Win rate:", f"{stats['win_rate']:.1f}%  ({stats['win_count']} win / {stats['loss_count']} loss)",
    )
    _summary_row("Average win:", _fmt_usd(stats["avg_win"]), color=_POSITIVE)
    _summary_row("Average loss:", _fmt_usd(stats["avg_loss"]), color=_NEGATIVE)
    _summary_row("Best single trade:", _fmt_usd(stats["best_trade"]), color=_POSITIVE)
    _summary_row("Worst single trade:", _fmt_usd(stats["worst_trade"]), color=_NEGATIVE)
    _summary_row("Total fees paid:", _fmt_usd(stats["total_fees"]))
    pdf.ln(4)

    # --- Trade history table ---
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(*_ACCENT)
    shown = trade_log[:MAX_TRADES_IN_REPORT]
    title = "Trade History"
    if len(trade_log) > MAX_TRADES_IN_REPORT:
        title += f" (most recent {MAX_TRADES_IN_REPORT} of {len(trade_log)})"
    pdf.cell(0, 8, title, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(1)

    if not shown:
        pdf.set_font("Helvetica", "", 11)
        pdf.set_text_color(*_MUTED)
        pdf.cell(0, 8, "No closed trades yet.", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.set_text_color(0, 0, 0)
    else:
        col_widths = (28, 22, 8, 22, 22, 24, 24, 36)
        headers = ("Closed", "Ticker", "Side", "Entry", "Exit", "P&L", "Fee", "Reason")
        pdf.set_font("Helvetica", "B", 8.5)
        pdf.set_fill_color(*_BRAND)
        pdf.set_text_color(255, 255, 255)
        for w, h in zip(col_widths, headers):
            pdf.cell(w, 7, h, border=0, fill=True)
        pdf.ln(7)
        pdf.set_text_color(0, 0, 0)

        for i, t in enumerate(shown):
            if pdf.get_y() > 275:
                pdf.add_page()
            pnl = float(t.get("realized_pnl_usd", 0.0))
            closed_at = str(t.get("closed_at", ""))[:16].replace("T", " ")
            side = "L" if t.get("side") != "short" else "S"
            reason = str(t.get("reason", ""))[:28]
            pdf.set_font("Helvetica", "", 8)
            pdf.set_fill_color(*_ROW_ALT)
            fill = i % 2 == 1
            pdf.cell(col_widths[0], 6, closed_at, fill=fill)
            pdf.cell(col_widths[1], 6, str(t.get("ticker", ""))[:12], fill=fill)
            pdf.cell(col_widths[2], 6, side, fill=fill)
            pdf.cell(col_widths[3], 6, f"{float(t.get('entry_price', 0.0)):.4f}", fill=fill)
            pdf.cell(col_widths[4], 6, f"{float(t.get('exit_price', 0.0)):.4f}", fill=fill)
            pdf.set_text_color(*(_POSITIVE if pnl >= 0 else _NEGATIVE))
            pdf.cell(col_widths[5], 6, _fmt_usd(pnl), fill=fill)
            pdf.set_text_color(0, 0, 0)
            pdf.cell(col_widths[6], 6, _fmt_usd(float(t.get("fee_usd", 0.0))), fill=fill)
            pdf.cell(col_widths[7], 6, reason, fill=fill)
            pdf.ln(6)

    return bytes(pdf.output())
